### ISSUE TITLE
Need extension metadata

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/etc-jupyterlab-telemetry#3]
When I click on the extension manager in jupyterhub I see the telemetry extension there but the icon is broken (should be the etc. icon) and the link doesn't go to the correct github location)

**Comment by adpatter** [comment]
OK. I will get this working and I will start keeping the JupyterHub instance more up to date.

**Comment by adpatter** [comment]
@cab938 Do you have an email address that I should use in the package.json file?  For example, is there a general email address for ETC?

**Comment by adpatter** [comment]
@cab938 I have reinstalled the extension into the **ETC Adpatter** JupyterHub environment.  Please let me know if you would like for it to be installed elsewhere.

**Comment by adpatter** [comment]
Both of the issues mentioned here have been resolved.
